# Generated by Django 2.0 on 2018-01-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'Avocat',
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('datedebut', models.DateField(db_column='dateDebut', primary_key=True, serialize=False)),
                ('datefin', models.DateField(blank=True, db_column='dateFin', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Disponibilite',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'Ecole',
            },
        ),
        migrations.CreateModel(
            name='Hebergeur',
            fields=[
                ('adressemail', models.CharField(db_column='adresseMail', max_length=250, primary_key=True, serialize=False)),
                ('facebook', models.CharField(blank=True, db_column='facebook', max_length=250, null=True)),
                ('signaturecharte', models.IntegerField(db_column='signatureCharte')),
                ('adressepostale', models.CharField(db_column='adressePostale', max_length=250)),
                ('capaciteaccueil', models.IntegerField(db_column='capaciteAccueil')),
                ('nblitsimple', models.IntegerField(blank=True, db_column='nbLitSimple', null=True)),
                ('nblitdouble', models.IntegerField(blank=True, db_column='nbLitDouble', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Hebergeur',
            },
        ),
        migrations.CreateModel(
            name='Jeune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'Jeune',
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'Langue',
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'Membre',
            },
        ),
        migrations.CreateModel(
            name='Nationalite',
            fields=[
                ('pays', models.CharField(db_column='pays', max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'Nationalite',
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'Personne',
            },
        ),
        migrations.CreateModel(
            name='Accueillir',
            fields=[
                ('datedebut', models.DateField(blank=True, db_column='dateDebut', null=True)),
                ('datefin', models.DateField(blank=True, db_column='dateFin', null=True)),
                ('commentaire', models.CharField(blank=True, db_column='commentaire', max_length=250, null=True)),
                ('adressemail', models.OneToOneField(db_column='adresseMail', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApplication.Hebergeur')),
            ],
            options={
                'managed': False,
                'db_table': 'accueillir',
            },
        ),
        migrations.CreateModel(
            name='Apprecier',
            fields=[
                ('adressemail', models.OneToOneField(db_column='adresseMail', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApplication.Hebergeur')),
            ],
            options={
                'managed': False,
                'db_table': 'apprecier',
            },
        ),
        migrations.CreateModel(
            name='Deprecier',
            fields=[
                ('adressemail', models.OneToOneField(db_column='adresseMail', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApplication.Hebergeur')),
            ],
            options={
                'managed': False,
                'db_table': 'deprecier',
            },
        ),
        migrations.CreateModel(
            name='Entente',
            fields=[
                ('idpersonne', models.OneToOneField(db_column='idPersonne', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='leJeune', serialize=False, to='webApplication.Personne')),
            ],
            options={
                'managed': False,
                'db_table': 'entente',
            },
        ),
        migrations.CreateModel(
            name='Mesentente',
            fields=[
                ('idpersonne', models.OneToOneField(db_column='idPersonne', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='UnJeune', serialize=False, to='webApplication.Personne')),
            ],
            options={
                'managed': False,
                'db_table': 'mesentente',
            },
        ),
        migrations.CreateModel(
            name='Parler',
            fields=[
                ('libelle', models.OneToOneField(db_column='libelle', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApplication.Langue')),
            ],
            options={
                'managed': False,
                'db_table': 'parler',
            },
        ),
    ]
